config/routes.rb
Rails.application.routes.draw do
  resources :uploads, except: :new do
    get :search, on: :collection, to: "upload_searches#show"
  end

  resources :clips, only: %i[create destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "healthcheck" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  root "uploads#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/audio_segment.rb
class AudioSegment < ApplicationRecord
  include Ranged

  belongs_to :upload
  has_one_attached :audio
end

app/models/clip.rb
##
# A clip is a user-initiated selection of a range of text within a transcript.
# It is created by selecting a start and end segment, and is associated with a transcript.
class Clip < ApplicationRecord
  include Ranged

  belongs_to :transcript
  has_one :upload, through: :transcript

  def segments
    @segments ||= transcript.segments.between_time(start_time, end_time).ordered
  end

  def text
    segments.map(&:text).join(" ")
  end
end

app/models/concerns/ranged.rb
module Ranged
  extend ActiveSupport::Concern

  def range
    start_time..end_time
  end

  class_methods do
    def between_time(start_time, end_time)
      where("start_time >= ? AND end_time <= ?", start_time, end_time)
    end

    def ordered
      order(:start_time)
    end
  end
end

app/models/segment.rb
class Segment < ApplicationRecord
  include Ranged

  belongs_to :transcript
  has_one :upload, through: :transcript

  def breaks?
    text.ends_with?(".") || text.ends_with?("?")
  end
end

app/models/summary.rb
class Summary < ApplicationRecord
  belongs_to :transcript
end

app/models/transcript.rb
##
# This class represents a transcript of a video.
# It has a one-to-many relationship with segments, clips, and a summary.
class Transcript < ApplicationRecord
  include Litesearch::Model
  belongs_to :upload
  has_many :segments, -> { ordered }, dependent: :destroy
  has_many :clips, dependent: :destroy
  has_one :summary, dependent: :destroy

  litesearch do |schema|
    schema.fields %i[text]
    schema.tokenizer :porter
  end
end

app/models/upload.rb
# frozen_string: true

##
# Stores the top-level file upload record
class Upload < ApplicationRecord
  UPLOAD_MIME_TYPES = %w[video/mp4 video/webm audio/mpeg].freeze
  DEFAULT_LANGUAGE = "en-NZ".freeze # TODO: Move to config

  has_one_attached :file
  has_one_attached :audio
  has_many :audio_segments, -> { order(:sequence_number) }, dependent: :destroy
  has_one :transcript, dependent: :destroy
  has_one :summary, through: :transcript
  has_many :clips, -> { ordered }, through: :transcript

  enum processing_stage: {
    "started" => "started",
    "pending" => "pending",
    "extracting_audio" => "extracting_audio",
    "transcribing" => "transcribing",
    "collating" => "collating",
    "summarising" => "summarising",
    "complete" => "complete"
  }

  validate :validate_file_content_type
  validate :validate_file_attached

  before_validation :default_language, on: :create
  before_validation :default_name, on: :create

  # When the model instance is changed, a message will sent over
  # ActionCable that notifies the page to reload.
  broadcasts_refreshes

  def video?
    file.content_type.start_with?('video/')
  end

  def audio?
    file.content_type.start_with?('audio/')
  end

  def processed?
    processing_ended_at.present?
  end

  def language_iso639_1
    language.split("-").first
  end

  def audio_extractable?
    file.attached? && (video? || audio?)
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  private

  def default_name
    name.presence || (self.name = file.filename.base)
  end

  def default_language
    self.language ||= DEFAULT_LANGUAGE
  end

  def validate_file_attached
    return if file.attached?

    errors.add(:file, :blank)
  end

  def validate_file_content_type
    return if file.attached? && UPLOAD_MIME_TYPES.include?(file.content_type)

    file.purge
    errors.add(:file, :invalid_content_type)
  end
end

app/models/upload_search.rb
##
# Performs a user-initiated search on the uploads table.
class UploadSearch
  attr_reader :term

  def initialize(term:, scope: Upload.all)
    @term = term
    @scope = scope
  end

  def results
    execute unless @executed

    @results
  end

  def execute
    @executed = true
    @results = execute_query
  end

  private

  def execute_query
    entity_search = @scope.where("summaries.entities->>'name' = :term OR summaries.entities->>'entity' = :term", term:)
    @scope.joins(transcript: :summary)
      .where(id: Transcript.search(term).pluck(:upload_id))
      .or(entity_search)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clips_controller.rb
##
# Controller for creating clips from segments.
class ClipsController < ApplicationController
  def create
    @clip = Clip.create(
      transcript_id: transcript_id,
      start_time: clip_param(:starts),
      end_time: clip_param(:ends))

    redirect_back fallback_location: @clip.upload
  end

  def destroy
    @clip = Clip.destroy(params[:id])

    redirect_back fallback_location: @clip.upload
  end

  private

  def clip_param(key)
    params.require(:clip).require(key)
  end

  def transcript_id
    clip_param(:transcript_id)
  end
end

app/controllers/upload_searches_controller.rb
class UploadSearchesController < ApplicationController
  def show
    term = params[:q].presence
    return redirect_to root_path if term.blank?

    @search = UploadSearch.new(term: term)
    @uploads = @search.results

    render template: "uploads/index"
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: %i[ show edit update destroy]

  # GET /uploads or /uploads.json
  def index
    @uploads = Upload.order(created_at: :desc)
  end

  # GET /uploads/1 or /uploads/1.json
  def show
    return render template: "uploads/processing" unless @upload.processed?

    render
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads or /uploads.json
  def create
    @upload = Upload.new(upload_params_for(:create))

    respond_to do |format|
      if @upload.save
        ProcessUploadJob.perform_later(@upload)

        format.html { redirect_to uploads_url, notice: t(".success") }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html do
          flash[:alert] = @upload.errors.full_messages.to_sentence
          redirect_back fallback_location: uploads_url
        end
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1 or /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params_for(:update))
        format.html { redirect_to upload_url(@upload), notice: t(".success") }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1 or /uploads/1.json
  def destroy
    @upload.destroy!

    respond_to do |format|
      format.html { redirect_to uploads_url, notice: t(:success) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_upload
    @upload = Upload.includes(transcript: %i[segments clips]).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def upload_params_for(action)
    params.require(:upload).permit(action == :create ? %i[name file] : [:name])
  end
end

app/helpers/application_helper.rb
##
# Application-wide helpers
module ApplicationHelper
  def from_search?
    referer = URI.parse(request.referer)
    referer.host == request.host && referer.path == search_uploads_path
  rescue URI::InvalidURIError
    false
  end

  def describe_play_time(seconds)
    Time.at(seconds).utc.strftime("%H:%M:%S")
  end

  def describe_play_time_range(from_seconds, to_seconds)
    [describe_play_time(from_seconds), describe_play_time(to_seconds)].join(" - ")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title><%= content_for?(:title) ? "#{yield(:title)} on " : "" %>Clippy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve  %>

    <%= content_for(:head) %>
  </head>

  <body class="min-vh-100">
    <% if flash[:alert] || flash[:notice] %>
      <div class="container mt-5 mb-3">
        <div class="alert alert-info" role="alert"><%= flash[:alert] || flash[:notice] %></div>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/uploads/_entities.html.erb
<% @upload.summary&.entities.each do |entity| %>
  <%= link_to "#{entity["name"] || entity["entity"]} (#{entity["type"]})", search_uploads_path(q: entity["name"] || entity["entity"]), class: "badge fs-6 my-2 bg-transparent text-decoration-none border text-wrap" %>
<% end %>

app/views/uploads/_transcript.html.erb
<section data-upload-sync-target="transcript" data-controller="clip" class="position-relative">
<%= form_with model: Clip.new, html: { style: "top:1rem;", class: "sticky-top alert alert-info d-flex justify-content-between align-items-center z-1" } do |f| %>
  <%= f.hidden_field :transcript_id, value: upload.transcript.to_param %>
  <%= f.hidden_field :starts, data: { clip_target: "rangeStartsInput" } %>
  <%= f.hidden_field :ends, data: { clip_target: "rangeEndsInput" } %>
  <div data-clip-target="message">[Select some text to clip]</div>
  <%= f.button "✂ Clip", class: "btn btn-sm btn-primary", data: { clip_target: "button" } %>
<% end %>

<% start_of_section = true %>
<% upload.transcript.segments.each_with_index do |segment, idx| %>
  <span class="transcript-segment" id="#secs-<%= segment.start_time.round %>" data-starts="<%= segment.start_time %>" data-ends="<%= segment.end_time %>">
    <%= content_tag :a,
                    "[#{describe_play_time(segment.start_time)}]",
                    id: dom_id(segment, :start),
                    data: { action: "upload-sync#scrubTo", starts: segment.start_time, ends: segment.end_time },
                    class: "user-select-none text-reset link-underline-light link-underline-opacity-0 link-underline-opacity-75-hover" if start_of_section -%>
    <%= content_tag :span, segment.text,
                    class: ('bg-primary' if @upload.transcript.clips.any? { |clip| clip.range.overlap?(segment.range)}) %>
  </span>
  <% if segment.breaks? %>
    <% start_of_section = true %>
    <br /><br />
  <% else %>
    <% start_of_section = false %>
  <% end %>
<% end %>
</section>

app/views/uploads/edit.html.erb
<% provide(:title, "Edit #{@upload.name}") %>

<div class="container my-5">
  <%= link_to "↰ '#{@upload.name}'", @upload, class: "mb-3 d-block" %>

  <%= form_with(model: @upload) do |form| %>
    <legend class="h1">Editing '<%= @upload.name %>'</legend>

    <div class="my-2">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control #{'is-invalid' if @upload.errors[:file].any?}" %>
      <% if @upload.errors[:name].any? %>
        <div class="invalid-feedback d-block">Name <%= @upload.errors[:name].to_sentence %></div>
      <% end %>
    </div>

    <div class="row mt-5 align-items-center justify-content-between">
      <div class="col-auto">
        <%= link_to "Back to '#{@upload.name}'", @upload %>
      </div>
      <div class="col-auto">
        <%= form.submit "Update", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/uploads/index.html.erb
<% provide(:title, "Uploads") %>

<div class="container py-5">
   <div class="row mb-5 align-items-center">
    <div class="col">
      <h1 class="h2 lh-1">
        Uploads
        <br />
        <%= form_with model: Upload.new, data: { controller: "upload auto-submit" } do |f| %>
          <%= f.file_field :file, direct_upload: true, data: { upload_target: "input", action: "change->auto-submit#submit" }, class: "visually-hidden form-control" %>
          <small class="fs-6">Drop a file anywhere to upload or
            <%= f.label :file, "select a file", class: "text-decoration-underline link-offset-3" %>
          </small>
        <% end %>
      <h1>
    </div>
    <%= form_with method: :get, url: search_uploads_path, html: { data: { turbo_frame: :uploads }, class: "col-auto" } do |f|%>
      <%= search_field_tag :q, params[:q],
                           placeholder: "Search",
                           class: "form-control form-control-lg",
                           data: { controller: "search", search_reset_path_value: uploads_path }
      %>
    <% end %>
  </div>

  <%= turbo_frame_tag :uploads do %>
    <%= content_tag(:h2, "Search results for '#{@search.term}'", class: "h4 mb-3") if @search %>

    <% @uploads.each do |upload| %>
      <%= turbo_stream_from upload %>
      <div class="row align-items-center position-relative mb-4 <%= 'opacity-50' unless upload.processed? %>">
          <div class="col-auto">
            <%= image_tag upload.file.preview(resize_to_fit: [128, 100]), class: "rounded" %>
          </div>

          <div class="col lh-sm">
            <h1 class="h5 mb-1"><%= upload.name %></h1>
            <small class="text-muted">
              Created at
              <%= time_tag upload.created_at, localize(upload.created_at, format: :long) %>
            </small>
            <% if upload.audio.analyzed? %>
            <br /><small class="text-muted">
              Duration:
              <%= describe_play_time(upload.audio.metadata["duration"]) %>
            </small>
            <% end %>
            <% if !upload.processed? && upload.processing_started_at %>
              <br /><small class="text-muted">Processing started at
                            <%= time_tag upload.processing_started_at, localize(upload.created_at, format: :long) %>
                            (<%= upload.processing_stage %>)
              </small>
            <% elsif !upload.processed? %>
              <br /><small class="text-muted">Waiting to process...</small>
            <% end %>
          </div>

          <% if upload.processed? %>
            <div class="col-auto">
              <%= link_to "View", upload, class: "stretched-link", data: { turbo_frame: "_top" } %>
            </div>
          <% end %>
      </div>
    <% end %>

    <% if @uploads.empty? && @search %>
      <div class="alert alert-info">
        No uploads found for "<%= @search.term %>".
        <%= link_to "View all uploads", uploads_path, class: "text-reset" %>
      </div>
    <% elsif @uploads.empty?  %>
      <div class="alert alert-info">
        No uploads added yet. Drop a file anywhere to upload.
      </div>
    <% end %>
  <% end %>
</div>

app/views/uploads/processing.html.erb
<% provide(:title, "#{@upload.name} is processing") %>

<%= turbo_stream_from @upload %>

<div class="justify-content-center align-items-center flex-column d-flex min-vh-100 min-vw-100">
  <div class="spinner-border text-primary" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
  <p class="mt-3">Upload is processing. Please wait...</p>
</div>

app/views/uploads/show.html.erb
<% provide(:title, @upload.name) %>

<div class="container-fluid container-lg my-5" data-controller="upload-sync">
  <% if from_search? %>
    <%= link_to "↰ Back to results", request.referer, class: "d-block mb-3 d-print-none" %>
  <% else %>
    <%= link_to "↰ All uploads", uploads_path, class: "d-block mb-3 d-print-none" %>
  <% end %>

  <div class="row align-items-center mb-5">
    <div class="col-12 col-lg">
      <h1><%= @upload.name %></h1>
    </div>
    <div class="col-auto">
      <div>
        Created at
        <%= time_tag @upload.created_at, localize(@upload.created_at, format: :long) %>
      </div>

      <div>
        Duration:
        <%= describe_play_time(@upload.audio.metadata["duration"]) %>
      </div>
    </div>
    <div class="col text-end col-lg-auto d-print-none">
      <%= link_to "Edit", edit_upload_path(@upload), class: "btn btn-primary" %>
      <%= link_to "Delete", @upload, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col-12 col-lg-9 fw-semibold">
      <%= simple_format @upload.summary&.text %>
    </div>

    <div class="col-12 col-lg-9 mb-4">
      <%= render "entities" %>
    </div>

    <div class="offset-3 offset-lg-2 d-none d-print-block">&nbsp;</div>

    <div class="col-5 col-lg-6 d-print-none">
      <% if @upload.video? %>
        <video
          controls
          class="mw-100 w-100 object-fit-contain rounded sticky-top mb-4"
          style="top: 20px;"
          poster="<%= url_for(@upload.file.preview(resize_to_fit: [1920, 1080])) %>"
          data-upload-sync-target="media">
          <source src="<%= url_for(@upload.file) %>" type="video/mp4">
          Your browser does not support the video tag.
        </video>
      <% elsif @upload.audio? %>
        <audio controls>
          <source src="<%= url_for(@upload.audio_url) %>" type="audio/mpeg">
          Your browser does not support the audio tag.
        </audio>
      <% else %>
        No preview is available for this file. <br>
        <%= link_to "Download", url_for(@upload.file), target: "_blank", download: true %>
      <% end %>

      <% @upload.clips.each do |clip| %>
        <div class="clip mb-4 d-flex border-start border-3 border-primary ps-3 mb-1">
          <figure>
            <blockquote class="mb-1"><%= clip.text %></blockquote>
            <figcaption class="d-flex justify-content-between align-items-end">
              <small><%= link_to describe_play_time_range(clip.start_time, clip.end_time), "#t=#{clip.start_time.round}s", data: { turbo: false } %></small>
            </figcaption>
          </figure>
          <%= button_to "", clip, class: "btn-close", method: :delete,
                              aria: { label: "Delete clip" },
                              title: "Delete clip",
                              data: { turbo_confirm: "Are you sure you want to delete this clip?" } %>
        </div>
      <% end%>

    </div>

    <div class="col-7 col-lg-6 col-print-12">
      <%= render "transcript", upload: @upload %>
    </div>
  </div>
</div>